import { MD3LightTheme as DefaultTheme } from "react-native-paper";
import { MD3DarkTheme as DefaultDarkTheme } from "react-native-paper";

export const ThemeGreen = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    card: '#607D8B',
    text: '#ffffff',
    border: '#546E7A',
    notification: '#3E2723',
    primary: "#1B5E20",
    onPrimary: "#ffffff",
    primaryContainer: "#e8ddff",
    onPrimaryContainer: "#2E7D32",
    secondary: "#615b71",
    onSecondary: "#ffffff",
    secondaryContainer: "#e8def8",
    onSecondaryContainer: "#1d192b",
    tertiary: "#7d5260",
    onTertiary: "#ffffff",
    tertiaryContainer: "#ffd9e3",
    onTertiaryContainer: "#31101d",
    error: "#ba1a1a",
    onError: "#ffffff",
    errorContainer: "#ffdada",
    onErrorContainer: "#410002",
    background: "#E8F5E9",
    onBackground: "#1c1b1e",
    surface: "#fffbff",
    onSurface: "#1c1b1e",
    surfaceVariant: "#e6e0ec",
    onSurfaceVariant: "#48454e",
    outline: "#79757f",
    outlineVariant: "#cac4cf",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#312f33",
    inverseOnSurface: "#f4eff4",
    inversePrimary: "#cebdff",
    elevation: {
      level0: "transparent",
      level1: "#f7f2fc",
      level2: "#f3edfa",
      level3: "#eee7f8",
      level4: "#ede5f7",
      level5: "#eae2f6"
    },
    surfaceDisabled: "#1c1b1e1f",
    onSurfaceDisabled: "#1c1b1e61",
    backdrop: "#322f3870"
  },
};

export const ThemeRed = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    card: '#607D8B',
    text: '#ffffff',
    border: '#546E7A',
    notification: '#3E2723',
    primary: "#D50000",
    onPrimary: "#ffffff",
    primaryContainer: "#e8ddff",
    onPrimaryContainer: "#E53935",
    secondary: "#615b71",
    onSecondary: "#ffffff",
    secondaryContainer: "#e8def8",
    onSecondaryContainer: "#1d192b",
    tertiary: "#7d5260",
    onTertiary: "#ffffff",
    tertiaryContainer: "#ffd9e3",
    onTertiaryContainer: "#31101d",
    error: "#ba1a1a",
    onError: "#ffffff",
    errorContainer: "#ffdada",
    onErrorContainer: "#410002",
    background: "#FFEBEE",
    onBackground: "#1c1b1e",
    surface: "#fffbff",
    onSurface: "#1c1b1e",
    surfaceVariant: "#e6e0ec",
    onSurfaceVariant: "#48454e",
    outline: "#79757f",
    outlineVariant: "#cac4cf",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#312f33",
    inverseOnSurface: "#f4eff4",
    inversePrimary: "#cebdff",
    elevation: {
      level0: "transparent",
      level1: "#f7f2fc",
      level2: "#f3edfa",
      level3: "#eee7f8",
      level4: "#ede5f7",
      level5: "#eae2f6"
    },
    surfaceDisabled: "#1c1b1e1f",
    onSurfaceDisabled: "#1c1b1e61",
    backdrop: "#322f3870"
  },
};

export const ThemePink = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    card: '#607D8B',
    text: '#ffffff',
    border: '#546E7A',
    notification: '#3E2723',
    primary: "#880E4F",
    onPrimary: "#ffffff",
    primaryContainer: "#e8ddff",
    onPrimaryContainer: "#EC407A",
    secondary: "#615b71",
    onSecondary: "#ffffff",
    secondaryContainer: "#e8def8",
    onSecondaryContainer: "#1d192b",
    tertiary: "#7d5260",
    onTertiary: "#ffffff",
    tertiaryContainer: "#ffd9e3",
    onTertiaryContainer: "#31101d",
    error: "#ba1a1a",
    onError: "#ffffff",
    errorContainer: "#ffdada",
    onErrorContainer: "#410002",
    background: "#FCE4EC",
    onBackground: "#1c1b1e",
    surface: "#fffbff",
    onSurface: "#1c1b1e",
    surfaceVariant: "#e6e0ec",
    onSurfaceVariant: "#48454e",
    outline: "#79757f",
    outlineVariant: "#cac4cf",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#312f33",
    inverseOnSurface: "#f4eff4",
    inversePrimary: "#cebdff",
    elevation: {
      level0: "transparent",
      level1: "#f7f2fc",
      level2: "#f3edfa",
      level3: "#eee7f8",
      level4: "#ede5f7",
      level5: "#eae2f6"
    },
    surfaceDisabled: "#1c1b1e1f",
    onSurfaceDisabled: "#1c1b1e61",
    backdrop: "#322f3870"
  },
};

export const ThemePurple = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    card: '#607D8B',
    text: '#ffffff',
    border: '#546E7A',
    notification: '#3E2723',
    primary: "#4A148C",
    onPrimary: "#ffffff",
    primaryContainer: "#e8ddff",
    onPrimaryContainer: "#7E57C2",
    secondary: "#615b71",
    onSecondary: "#ffffff",
    secondaryContainer: "#e8def8",
    onSecondaryContainer: "#1d192b",
    tertiary: "#7d5260",
    onTertiary: "#ffffff",
    tertiaryContainer: "#ffd9e3",
    onTertiaryContainer: "#31101d",
    error: "#ba1a1a",
    onError: "#ffffff",
    errorContainer: "#ffdada",
    onErrorContainer: "#410002",
    background: "#F3E5F5",
    onBackground: "#1c1b1e",
    surface: "#fffbff",
    onSurface: "#1c1b1e",
    surfaceVariant: "#e6e0ec",
    onSurfaceVariant: "#48454e",
    outline: "#79757f",
    outlineVariant: "#cac4cf",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#312f33",
    inverseOnSurface: "#f4eff4",
    inversePrimary: "#cebdff",
    elevation: {
      level0: "transparent",
      level1: "#f7f2fc",
      level2: "#f3edfa",
      level3: "#eee7f8",
      level4: "#ede5f7",
      level5: "#eae2f6"
    },
    surfaceDisabled: "#1c1b1e1f",
    onSurfaceDisabled: "#1c1b1e61",
    backdrop: "#322f3870"
  },
};


export const ThemeCyan = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    card: '#607D8B',
    text: '#ffffff',
    border: '#546E7A',
    notification: '#3E2723',
    primary: "#006064",
    onPrimary: "#ffffff",
    primaryContainer: "#e8ddff",
    onPrimaryContainer: "#26A69A",
    secondary: "#615b71",
    onSecondary: "#ffffff",
    secondaryContainer: "#e8def8",
    onSecondaryContainer: "#1d192b",
    tertiary: "#7d5260",
    onTertiary: "#ffffff",
    tertiaryContainer: "#ffd9e3",
    onTertiaryContainer: "#31101d",
    error: "#ba1a1a",
    onError: "#ffffff",
    errorContainer: "#ffdada",
    onErrorContainer: "#410002",
    background: "#E0F7FA",
    onBackground: "#1c1b1e",
    surface: "#fffbff",
    onSurface: "#1c1b1e",
    surfaceVariant: "#e6e0ec",
    onSurfaceVariant: "#48454e",
    outline: "#79757f",
    outlineVariant: "#cac4cf",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#312f33",
    inverseOnSurface: "#f4eff4",
    inversePrimary: "#cebdff",
    elevation: {
      level0: "transparent",
      level1: "#f7f2fc",
      level2: "#f3edfa",
      level3: "#eee7f8",
      level4: "#ede5f7",
      level5: "#eae2f6"
    },
    surfaceDisabled: "#1c1b1e1f",
    onSurfaceDisabled: "#1c1b1e61",
    backdrop: "#322f3870"
  },
};

export const ThemeAmber = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    card: '#607D8B',
    text: '#ffffff',
    border: '#546E7A',
    notification: '#3E2723',
    primary: "#FF6F00",
    onPrimary: "#ffffff",
    primaryContainer: "#e8ddff",
    onPrimaryContainer: "#FFA726",
    secondary: "#615b71",
    onSecondary: "#ffffff",
    secondaryContainer: "#e8def8",
    onSecondaryContainer: "#1d192b",
    tertiary: "#7d5260",
    onTertiary: "#ffffff",
    tertiaryContainer: "#ffd9e3",
    onTertiaryContainer: "#31101d",
    error: "#ba1a1a",
    onError: "#ffffff",
    errorContainer: "#ffdada",
    onErrorContainer: "#410002",
    background: "#FFF8E1",
    onBackground: "#1c1b1e",
    surface: "#fffbff",
    onSurface: "#1c1b1e",
    surfaceVariant: "#e6e0ec",
    onSurfaceVariant: "#48454e",
    outline: "#79757f",
    outlineVariant: "#cac4cf",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#312f33",
    inverseOnSurface: "#f4eff4",
    inversePrimary: "#cebdff",
    elevation: {
      level0: "transparent",
      level1: "#f7f2fc",
      level2: "#f3edfa",
      level3: "#eee7f8",
      level4: "#ede5f7",
      level5: "#eae2f6"
    },
    surfaceDisabled: "#1c1b1e1f",
    onSurfaceDisabled: "#1c1b1e61",
    backdrop: "#322f3870"
  },
};

export const ThemeOrange = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    card: '#607D8B',
    text: '#ffffff',
    border: '#546E7A',
    notification: '#3E2723',
    primary: "#E65100",
    onPrimary: "#ffffff",
    primaryContainer: "#e8ddff",
    onPrimaryContainer: "#FFA726",
    secondary: "#615b71",
    onSecondary: "#ffffff",
    secondaryContainer: "#e8def8",
    onSecondaryContainer: "#1d192b",
    tertiary: "#7d5260",
    onTertiary: "#ffffff",
    tertiaryContainer: "#ffd9e3",
    onTertiaryContainer: "#31101d",
    error: "#ba1a1a",
    onError: "#ffffff",
    errorContainer: "#ffdada",
    onErrorContainer: "#410002",
    background: "#fffbff",
    onBackground: "#FFF3E0",
    surface: "#fffbff",
    onSurface: "#1c1b1e",
    surfaceVariant: "#e6e0ec",
    onSurfaceVariant: "#48454e",
    outline: "#79757f",
    outlineVariant: "#cac4cf",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#312f33",
    inverseOnSurface: "#f4eff4",
    inversePrimary: "#cebdff",
    elevation: {
      level0: "transparent",
      level1: "#f7f2fc",
      level2: "#f3edfa",
      level3: "#eee7f8",
      level4: "#ede5f7",
      level5: "#eae2f6"
    },
    surfaceDisabled: "#1c1b1e1f",
    onSurfaceDisabled: "#1c1b1e61",
    backdrop: "#322f3870"
  },
};

export const ThemeDeepOrange = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    card: '#607D8B',
    text: '#ffffff',
    border: '#546E7A',
    notification: '#3E2723',
    primary: "#BF360C",
    onPrimary: "#ffffff",
    primaryContainer: "#e8ddff",
    onPrimaryContainer: "#FF7043",
    secondary: "#615b71",
    onSecondary: "#ffffff",
    secondaryContainer: "#e8def8",
    onSecondaryContainer: "#1d192b",
    tertiary: "#7d5260",
    onTertiary: "#ffffff",
    tertiaryContainer: "#ffd9e3",
    onTertiaryContainer: "#31101d",
    error: "#ba1a1a",
    onError: "#ffffff",
    errorContainer: "#ffdada",
    onErrorContainer: "#410002",
    background: "#FBE9E7",
    onBackground: "#1c1b1e",
    surface: "#fffbff",
    onSurface: "#1c1b1e",
    surfaceVariant: "#e6e0ec",
    onSurfaceVariant: "#48454e",
    outline: "#79757f",
    outlineVariant: "#cac4cf",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#312f33",
    inverseOnSurface: "#f4eff4",
    inversePrimary: "#cebdff",
    elevation: {
      level0: "transparent",
      level1: "#f7f2fc",
      level2: "#f3edfa",
      level3: "#eee7f8",
      level4: "#ede5f7",
      level5: "#eae2f6"
    },
    surfaceDisabled: "#1c1b1e1f",
    onSurfaceDisabled: "#1c1b1e61",
    backdrop: "#322f3870"
  },
};

export const ThemeBrown = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    card: '#607D8B',
    text: '#ffffff',
    border: '#546E7A',
    notification: '#3E2723',
    primary: "#3E2723",
    onPrimary: "#ffffff",
    primaryContainer: "#e8ddff",
    onPrimaryContainer: "#8D6E63",
    secondary: "#615b71",
    onSecondary: "#ffffff",
    secondaryContainer: "#e8def8",
    onSecondaryContainer: "#1d192b",
    tertiary: "#7d5260",
    onTertiary: "#ffffff",
    tertiaryContainer: "#ffd9e3",
    onTertiaryContainer: "#31101d",
    error: "#ba1a1a",
    onError: "#ffffff",
    errorContainer: "#ffdada",
    onErrorContainer: "#410002",
    background: "#EFEBE9",
    onBackground: "#1c1b1e",
    surface: "#fffbff",
    onSurface: "#1c1b1e",
    surfaceVariant: "#e6e0ec",
    onSurfaceVariant: "#48454e",
    outline: "#79757f",
    outlineVariant: "#cac4cf",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#312f33",
    inverseOnSurface: "#f4eff4",
    inversePrimary: "#cebdff",
    elevation: {
      level0: "transparent",
      level1: "#f7f2fc",
      level2: "#f3edfa",
      level3: "#eee7f8",
      level4: "#ede5f7",
      level5: "#eae2f6"
    },
    surfaceDisabled: "#1c1b1e1f",
    onSurfaceDisabled: "#1c1b1e61",
    backdrop: "#322f3870"
  },
};

export const ThemeIndigo = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    card: '#607D8B',
    text: '#ffffff',
    border: '#546E7A',
    notification: '#3E2723',
    primary: "#1A237E",
    onPrimary: "#ffffff",
    primaryContainer: "#e8ddff",
    onPrimaryContainer: "#21005d",
    secondary: "#615b71",
    onSecondary: "#ffffff",
    secondaryContainer: "#e8def8",
    onSecondaryContainer: "#1d192b",
    tertiary: "#7d5260",
    onTertiary: "#ffffff",
    tertiaryContainer: "#ffd9e3",
    onTertiaryContainer: "#31101d",
    error: "#ba1a1a",
    onError: "#ffffff",
    errorContainer: "#ffdada",
    onErrorContainer: "#410002",
    background: "#fffbff",
    onBackground: "#1c1b1e",
    surface: "#fffbff",
    onSurface: "#1c1b1e",
    surfaceVariant: "#e6e0ec",
    onSurfaceVariant: "#48454e",
    outline: "#79757f",
    outlineVariant: "#cac4cf",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#312f33",
    inverseOnSurface: "#f4eff4",
    inversePrimary: "#cebdff",
    elevation: {
      level0: "transparent",
      level1: "#f7f2fc",
      level2: "#f3edfa",
      level3: "#eee7f8",
      level4: "#ede5f7",
      level5: "#eae2f6"
    },
    surfaceDisabled: "#1c1b1e1f",
    onSurfaceDisabled: "#1c1b1e61",
    backdrop: "#322f3870"
  },
};

export const ThemeBlue = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    card: '#607D8B',
    text: '#ffffff',
    border: '#546E7A',
    notification: '#3E2723',
    primary: "#0D47A1",
    onPrimary: "#ffffff",
    primaryContainer: "#e8ddff",
    onPrimaryContainer: "#21005d",
    secondary: "#615b71",
    onSecondary: "#ffffff",
    secondaryContainer: "#e8def8",
    onSecondaryContainer: "#1d192b",
    tertiary: "#7d5260",
    onTertiary: "#ffffff",
    tertiaryContainer: "#ffd9e3",
    onTertiaryContainer: "#31101d",
    error: "#ba1a1a",
    onError: "#ffffff",
    errorContainer: "#ffdada",
    onErrorContainer: "#410002",
    background: "#fffbff",
    onBackground: "#1c1b1e",
    surface: "#fffbff",
    onSurface: "#1c1b1e",
    surfaceVariant: "#e6e0ec",
    onSurfaceVariant: "#48454e",
    outline: "#79757f",
    outlineVariant: "#cac4cf",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#312f33",
    inverseOnSurface: "#f4eff4",
    inversePrimary: "#cebdff",
    elevation: {
      level0: "transparent",
      level1: "#f7f2fc",
      level2: "#f3edfa",
      level3: "#eee7f8",
      level4: "#ede5f7",
      level5: "#eae2f6"
    },
    surfaceDisabled: "#1c1b1e1f",
    onSurfaceDisabled: "#1c1b1e61",
    backdrop: "#322f3870"
  },
};


export const AppDarkTheme = {
  ...DefaultDarkTheme,
  colors: {
    ...DefaultDarkTheme.colors,
    card: '#607D8B',
    text: '#ffffff',
    border: '#546E7A',
    notification: '#3E2723',
    primary: "#212121",
    onPrimary: "#E0E0E0",
    primaryContainer: "#E0E0E0",
    onPrimaryContainer: "#f0dbff",
    secondary: "#d0c1da",
    onSecondary: "#362c3f",
    secondaryContainer: "#4d4357",
    onSecondaryContainer: "#edddf6",
    tertiary: "#f3b7be",
    onTertiary: "#4b252b",
    tertiaryContainer: "#653a41",
    onTertiaryContainer: "#ffd9dd",
    error: "#ffb4ab",
    onError: "#690005",
    errorContainer: "#93000a",
    onErrorContainer: "#ffb4ab",
    background: "#1d1b1e",
    onBackground: "#e7e1e5",
    surface: "#1d1b1e",
    onSurface: "#e7e1e5",
    surfaceVariant: "#4a454e",
    onSurfaceVariant: "#ccc4ce",
    outline: "#968e98",
    outlineVariant: "#4a454e",
    shadow: "#000000",
    scrim: "#000000",
    inverseSurface: "#e7e1e5",
    inverseOnSurface: "#322f33",
    inversePrimary: "#E0E0E0",
    elevation: {
      level0: "transparent",
      level1: "#272329",
      level2: "#2c2830",
      level3: "#322c37",
      level4: "#342e39",
      level5: "#38313e"
    },
    surfaceDisabled: "#e7e1e51f", 
    onSurfaceDisabled: "#e7e1e561",
    backdrop: "#332f3770"
  },
};